// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventChat.proto

package com.example.authclientproto;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool IsOpen = 2;</code>
   * @return The isOpen.
   */
  boolean getIsOpen();

  /**
   * <code>string Description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string Description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string Tags = 4;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string Tags = 4;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string Tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string Tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>string Resource = 5;</code>
   * @return The resource.
   */
  java.lang.String getResource();
  /**
   * <code>string Resource = 5;</code>
   * @return The bytes for resource.
   */
  com.google.protobuf.ByteString
      getResourceBytes();

  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */
  int getMoreCount();
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */
  boolean containsMore(
      java.lang.String key);
  /**
   * Use {@link #getMoreMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMore();
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMoreMap();
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */

  java.lang.String getMoreOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */

  java.lang.String getMoreOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string Members = 8;</code>
   * @return A list containing the members.
   */
  java.util.List<java.lang.String>
      getMembersList();
  /**
   * <code>repeated string Members = 8;</code>
   * @return The count of members.
   */
  int getMembersCount();
  /**
   * <code>repeated string Members = 8;</code>
   * @param index The index of the element to return.
   * @return The members at the given index.
   */
  java.lang.String getMembers(int index);
  /**
   * <code>repeated string Members = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the members at the given index.
   */
  com.google.protobuf.ByteString
      getMembersBytes(int index);

  /**
   * <code>.google.protobuf.Timestamp Creation = 9;</code>
   * @return Whether the creation field is set.
   */
  boolean hasCreation();
  /**
   * <code>.google.protobuf.Timestamp Creation = 9;</code>
   * @return The creation.
   */
  com.google.protobuf.Timestamp getCreation();
  /**
   * <code>.google.protobuf.Timestamp Creation = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreationOrBuilder();

  /**
   * <code>string Creator = 10;</code>
   * @return The creator.
   */
  java.lang.String getCreator();
  /**
   * <code>string Creator = 10;</code>
   * @return The bytes for creator.
   */
  com.google.protobuf.ByteString
      getCreatorBytes();

  /**
   * <code>string Chat = 12;</code>
   * @return The chat.
   */
  java.lang.String getChat();
  /**
   * <code>string Chat = 12;</code>
   * @return The bytes for chat.
   */
  com.google.protobuf.ByteString
      getChatBytes();

  /**
   * <pre>
   * in person
   * </pre>
   *
   * <code>.pb.PhysicalMeet Physical = 20;</code>
   * @return Whether the physical field is set.
   */
  boolean hasPhysical();
  /**
   * <pre>
   * in person
   * </pre>
   *
   * <code>.pb.PhysicalMeet Physical = 20;</code>
   * @return The physical.
   */
  com.example.authclientproto.PhysicalMeet getPhysical();
  /**
   * <pre>
   * in person
   * </pre>
   *
   * <code>.pb.PhysicalMeet Physical = 20;</code>
   */
  com.example.authclientproto.PhysicalMeetOrBuilder getPhysicalOrBuilder();

  /**
   * <pre>
   * online
   * </pre>
   *
   * <code>.pb.OnlineMeet Online = 30;</code>
   * @return Whether the online field is set.
   */
  boolean hasOnline();
  /**
   * <pre>
   * online
   * </pre>
   *
   * <code>.pb.OnlineMeet Online = 30;</code>
   * @return The online.
   */
  com.example.authclientproto.OnlineMeet getOnline();
  /**
   * <pre>
   * online
   * </pre>
   *
   * <code>.pb.OnlineMeet Online = 30;</code>
   */
  com.example.authclientproto.OnlineMeetOrBuilder getOnlineOrBuilder();
}
