// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventChat.proto

package com.example.authclientproto;

/**
 * Protobuf type {@code pb.Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    name_ = "";
    description_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    resource_ = "";
    members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    creator_ = "";
    chat_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Event();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            isOpen_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tags_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            resource_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              more_ = com.google.protobuf.MapField.newMapField(
                  MoreDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            more__ = input.readMessage(
                MoreDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            more_.getMutableMap().put(
                more__.getKey(), more__.getValue());
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              members_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            members_.add(s);
            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (creation_ != null) {
              subBuilder = creation_.toBuilder();
            }
            creation_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(creation_);
              creation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            creator_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            chat_ = s;
            break;
          }
          case 162: {
            com.example.authclientproto.PhysicalMeet.Builder subBuilder = null;
            if (physical_ != null) {
              subBuilder = physical_.toBuilder();
            }
            physical_ = input.readMessage(com.example.authclientproto.PhysicalMeet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(physical_);
              physical_ = subBuilder.buildPartial();
            }

            break;
          }
          case 242: {
            com.example.authclientproto.OnlineMeet.Builder subBuilder = null;
            if (online_ != null) {
              subBuilder = online_.toBuilder();
            }
            online_ = input.readMessage(com.example.authclientproto.OnlineMeet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(online_);
              online_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        members_ = members_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.authclientproto.ClientProto.internal_static_pb_Event_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetMore();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.authclientproto.ClientProto.internal_static_pb_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.authclientproto.Event.class, com.example.authclientproto.Event.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string Name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOPEN_FIELD_NUMBER = 2;
  private boolean isOpen_;
  /**
   * <code>bool IsOpen = 2;</code>
   * @return The isOpen.
   */
  @java.lang.Override
  public boolean getIsOpen() {
    return isOpen_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string Description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string Description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <code>repeated string Tags = 4;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated string Tags = 4;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated string Tags = 4;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated string Tags = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int RESOURCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object resource_;
  /**
   * <code>string Resource = 5;</code>
   * @return The resource.
   */
  @java.lang.Override
  public java.lang.String getResource() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resource_ = s;
      return s;
    }
  }
  /**
   * <code>string Resource = 5;</code>
   * @return The bytes for resource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceBytes() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MORE_FIELD_NUMBER = 6;
  private static final class MoreDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.example.authclientproto.ClientProto.internal_static_pb_Event_MoreEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> more_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMore() {
    if (more_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MoreDefaultEntryHolder.defaultEntry);
    }
    return more_;
  }

  public int getMoreCount() {
    return internalGetMore().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */

  @java.lang.Override
  public boolean containsMore(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMore().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMoreMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMore() {
    return getMoreMap();
  }
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMoreMap() {
    return internalGetMore().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */
  @java.lang.Override

  public java.lang.String getMoreOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMore().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; More = 6;</code>
   */
  @java.lang.Override

  public java.lang.String getMoreOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMore().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int MEMBERS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList members_;
  /**
   * <code>repeated string Members = 8;</code>
   * @return A list containing the members.
   */
  public com.google.protobuf.ProtocolStringList
      getMembersList() {
    return members_;
  }
  /**
   * <code>repeated string Members = 8;</code>
   * @return The count of members.
   */
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated string Members = 8;</code>
   * @param index The index of the element to return.
   * @return The members at the given index.
   */
  public java.lang.String getMembers(int index) {
    return members_.get(index);
  }
  /**
   * <code>repeated string Members = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the members at the given index.
   */
  public com.google.protobuf.ByteString
      getMembersBytes(int index) {
    return members_.getByteString(index);
  }

  public static final int CREATION_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp creation_;
  /**
   * <code>.google.protobuf.Timestamp Creation = 9;</code>
   * @return Whether the creation field is set.
   */
  @java.lang.Override
  public boolean hasCreation() {
    return creation_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp Creation = 9;</code>
   * @return The creation.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreation() {
    return creation_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creation_;
  }
  /**
   * <code>.google.protobuf.Timestamp Creation = 9;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreationOrBuilder() {
    return getCreation();
  }

  public static final int CREATOR_FIELD_NUMBER = 10;
  private volatile java.lang.Object creator_;
  /**
   * <code>string Creator = 10;</code>
   * @return The creator.
   */
  @java.lang.Override
  public java.lang.String getCreator() {
    java.lang.Object ref = creator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creator_ = s;
      return s;
    }
  }
  /**
   * <code>string Creator = 10;</code>
   * @return The bytes for creator.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatorBytes() {
    java.lang.Object ref = creator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAT_FIELD_NUMBER = 12;
  private volatile java.lang.Object chat_;
  /**
   * <code>string Chat = 12;</code>
   * @return The chat.
   */
  @java.lang.Override
  public java.lang.String getChat() {
    java.lang.Object ref = chat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chat_ = s;
      return s;
    }
  }
  /**
   * <code>string Chat = 12;</code>
   * @return The bytes for chat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatBytes() {
    java.lang.Object ref = chat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHYSICAL_FIELD_NUMBER = 20;
  private com.example.authclientproto.PhysicalMeet physical_;
  /**
   * <pre>
   * in person
   * </pre>
   *
   * <code>.pb.PhysicalMeet Physical = 20;</code>
   * @return Whether the physical field is set.
   */
  @java.lang.Override
  public boolean hasPhysical() {
    return physical_ != null;
  }
  /**
   * <pre>
   * in person
   * </pre>
   *
   * <code>.pb.PhysicalMeet Physical = 20;</code>
   * @return The physical.
   */
  @java.lang.Override
  public com.example.authclientproto.PhysicalMeet getPhysical() {
    return physical_ == null ? com.example.authclientproto.PhysicalMeet.getDefaultInstance() : physical_;
  }
  /**
   * <pre>
   * in person
   * </pre>
   *
   * <code>.pb.PhysicalMeet Physical = 20;</code>
   */
  @java.lang.Override
  public com.example.authclientproto.PhysicalMeetOrBuilder getPhysicalOrBuilder() {
    return getPhysical();
  }

  public static final int ONLINE_FIELD_NUMBER = 30;
  private com.example.authclientproto.OnlineMeet online_;
  /**
   * <pre>
   * online
   * </pre>
   *
   * <code>.pb.OnlineMeet Online = 30;</code>
   * @return Whether the online field is set.
   */
  @java.lang.Override
  public boolean hasOnline() {
    return online_ != null;
  }
  /**
   * <pre>
   * online
   * </pre>
   *
   * <code>.pb.OnlineMeet Online = 30;</code>
   * @return The online.
   */
  @java.lang.Override
  public com.example.authclientproto.OnlineMeet getOnline() {
    return online_ == null ? com.example.authclientproto.OnlineMeet.getDefaultInstance() : online_;
  }
  /**
   * <pre>
   * online
   * </pre>
   *
   * <code>.pb.OnlineMeet Online = 30;</code>
   */
  @java.lang.Override
  public com.example.authclientproto.OnlineMeetOrBuilder getOnlineOrBuilder() {
    return getOnline();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (isOpen_ != false) {
      output.writeBool(2, isOpen_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tags_.getRaw(i));
    }
    if (!getResourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resource_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMore(),
        MoreDefaultEntryHolder.defaultEntry,
        6);
    for (int i = 0; i < members_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, members_.getRaw(i));
    }
    if (creation_ != null) {
      output.writeMessage(9, getCreation());
    }
    if (!getCreatorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, creator_);
    }
    if (!getChatBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, chat_);
    }
    if (physical_ != null) {
      output.writeMessage(20, getPhysical());
    }
    if (online_ != null) {
      output.writeMessage(30, getOnline());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (isOpen_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isOpen_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (!getResourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resource_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMore().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      more__ = MoreDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, more__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < members_.size(); i++) {
        dataSize += computeStringSizeNoTag(members_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMembersList().size();
    }
    if (creation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getCreation());
    }
    if (!getCreatorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, creator_);
    }
    if (!getChatBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, chat_);
    }
    if (physical_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getPhysical());
    }
    if (online_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(30, getOnline());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.authclientproto.Event)) {
      return super.equals(obj);
    }
    com.example.authclientproto.Event other = (com.example.authclientproto.Event) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getIsOpen()
        != other.getIsOpen()) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getResource()
        .equals(other.getResource())) return false;
    if (!internalGetMore().equals(
        other.internalGetMore())) return false;
    if (!getMembersList()
        .equals(other.getMembersList())) return false;
    if (hasCreation() != other.hasCreation()) return false;
    if (hasCreation()) {
      if (!getCreation()
          .equals(other.getCreation())) return false;
    }
    if (!getCreator()
        .equals(other.getCreator())) return false;
    if (!getChat()
        .equals(other.getChat())) return false;
    if (hasPhysical() != other.hasPhysical()) return false;
    if (hasPhysical()) {
      if (!getPhysical()
          .equals(other.getPhysical())) return false;
    }
    if (hasOnline() != other.hasOnline()) return false;
    if (hasOnline()) {
      if (!getOnline()
          .equals(other.getOnline())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ISOPEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOpen());
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getResource().hashCode();
    if (!internalGetMore().getMap().isEmpty()) {
      hash = (37 * hash) + MORE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMore().hashCode();
    }
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    if (hasCreation()) {
      hash = (37 * hash) + CREATION_FIELD_NUMBER;
      hash = (53 * hash) + getCreation().hashCode();
    }
    hash = (37 * hash) + CREATOR_FIELD_NUMBER;
    hash = (53 * hash) + getCreator().hashCode();
    hash = (37 * hash) + CHAT_FIELD_NUMBER;
    hash = (53 * hash) + getChat().hashCode();
    if (hasPhysical()) {
      hash = (37 * hash) + PHYSICAL_FIELD_NUMBER;
      hash = (53 * hash) + getPhysical().hashCode();
    }
    if (hasOnline()) {
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + getOnline().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.authclientproto.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.authclientproto.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.authclientproto.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.authclientproto.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.Event)
      com.example.authclientproto.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.authclientproto.ClientProto.internal_static_pb_Event_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMore();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableMore();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.authclientproto.ClientProto.internal_static_pb_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.authclientproto.Event.class, com.example.authclientproto.Event.Builder.class);
    }

    // Construct using com.example.authclientproto.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      isOpen_ = false;

      description_ = "";

      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      resource_ = "";

      internalGetMutableMore().clear();
      members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (creationBuilder_ == null) {
        creation_ = null;
      } else {
        creation_ = null;
        creationBuilder_ = null;
      }
      creator_ = "";

      chat_ = "";

      if (physicalBuilder_ == null) {
        physical_ = null;
      } else {
        physical_ = null;
        physicalBuilder_ = null;
      }
      if (onlineBuilder_ == null) {
        online_ = null;
      } else {
        online_ = null;
        onlineBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.authclientproto.ClientProto.internal_static_pb_Event_descriptor;
    }

    @java.lang.Override
    public com.example.authclientproto.Event getDefaultInstanceForType() {
      return com.example.authclientproto.Event.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.authclientproto.Event build() {
      com.example.authclientproto.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.authclientproto.Event buildPartial() {
      com.example.authclientproto.Event result = new com.example.authclientproto.Event(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.isOpen_ = isOpen_;
      result.description_ = description_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tags_ = tags_;
      result.resource_ = resource_;
      result.more_ = internalGetMore();
      result.more_.makeImmutable();
      if (((bitField0_ & 0x00000004) != 0)) {
        members_ = members_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.members_ = members_;
      if (creationBuilder_ == null) {
        result.creation_ = creation_;
      } else {
        result.creation_ = creationBuilder_.build();
      }
      result.creator_ = creator_;
      result.chat_ = chat_;
      if (physicalBuilder_ == null) {
        result.physical_ = physical_;
      } else {
        result.physical_ = physicalBuilder_.build();
      }
      if (onlineBuilder_ == null) {
        result.online_ = online_;
      } else {
        result.online_ = onlineBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.authclientproto.Event) {
        return mergeFrom((com.example.authclientproto.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.authclientproto.Event other) {
      if (other == com.example.authclientproto.Event.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getIsOpen() != false) {
        setIsOpen(other.getIsOpen());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.getResource().isEmpty()) {
        resource_ = other.resource_;
        onChanged();
      }
      internalGetMutableMore().mergeFrom(
          other.internalGetMore());
      if (!other.members_.isEmpty()) {
        if (members_.isEmpty()) {
          members_ = other.members_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureMembersIsMutable();
          members_.addAll(other.members_);
        }
        onChanged();
      }
      if (other.hasCreation()) {
        mergeCreation(other.getCreation());
      }
      if (!other.getCreator().isEmpty()) {
        creator_ = other.creator_;
        onChanged();
      }
      if (!other.getChat().isEmpty()) {
        chat_ = other.chat_;
        onChanged();
      }
      if (other.hasPhysical()) {
        mergePhysical(other.getPhysical());
      }
      if (other.hasOnline()) {
        mergeOnline(other.getOnline());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.authclientproto.Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.authclientproto.Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string Name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private boolean isOpen_ ;
    /**
     * <code>bool IsOpen = 2;</code>
     * @return The isOpen.
     */
    @java.lang.Override
    public boolean getIsOpen() {
      return isOpen_;
    }
    /**
     * <code>bool IsOpen = 2;</code>
     * @param value The isOpen to set.
     * @return This builder for chaining.
     */
    public Builder setIsOpen(boolean value) {
      
      isOpen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool IsOpen = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOpen() {
      
      isOpen_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string Description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string Description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Tags = 4;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object resource_ = "";
    /**
     * <code>string Resource = 5;</code>
     * @return The resource.
     */
    public java.lang.String getResource() {
      java.lang.Object ref = resource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Resource = 5;</code>
     * @return The bytes for resource.
     */
    public com.google.protobuf.ByteString
        getResourceBytes() {
      java.lang.Object ref = resource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Resource = 5;</code>
     * @param value The resource to set.
     * @return This builder for chaining.
     */
    public Builder setResource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Resource = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearResource() {
      
      resource_ = getDefaultInstance().getResource();
      onChanged();
      return this;
    }
    /**
     * <code>string Resource = 5;</code>
     * @param value The bytes for resource to set.
     * @return This builder for chaining.
     */
    public Builder setResourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resource_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> more_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMore() {
      if (more_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MoreDefaultEntryHolder.defaultEntry);
      }
      return more_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMore() {
      onChanged();;
      if (more_ == null) {
        more_ = com.google.protobuf.MapField.newMapField(
            MoreDefaultEntryHolder.defaultEntry);
      }
      if (!more_.isMutable()) {
        more_ = more_.copy();
      }
      return more_;
    }

    public int getMoreCount() {
      return internalGetMore().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */

    @java.lang.Override
    public boolean containsMore(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMore().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMoreMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMore() {
      return getMoreMap();
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMoreMap() {
      return internalGetMore().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getMoreOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMore().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getMoreOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMore().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMore() {
      internalGetMutableMore().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */

    public Builder removeMore(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMore().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMore() {
      return internalGetMutableMore().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */
    public Builder putMore(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMore().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; More = 6;</code>
     */

    public Builder putAllMore(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMore().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.LazyStringList members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        members_ = new com.google.protobuf.LazyStringArrayList(members_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @return A list containing the members.
     */
    public com.google.protobuf.ProtocolStringList
        getMembersList() {
      return members_.getUnmodifiableView();
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @return The count of members.
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @param index The index of the element to return.
     * @return The members at the given index.
     */
    public java.lang.String getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the members at the given index.
     */
    public com.google.protobuf.ByteString
        getMembersBytes(int index) {
      return members_.getByteString(index);
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @param index The index to set the value at.
     * @param value The members to set.
     * @return This builder for chaining.
     */
    public Builder setMembers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
      members_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @param value The members to add.
     * @return This builder for chaining.
     */
    public Builder addMembers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
      members_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @param values The members to add.
     * @return This builder for chaining.
     */
    public Builder addAllMembers(
        java.lang.Iterable<java.lang.String> values) {
      ensureMembersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, members_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMembers() {
      members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string Members = 8;</code>
     * @param value The bytes of the members to add.
     * @return This builder for chaining.
     */
    public Builder addMembersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMembersIsMutable();
      members_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp creation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> creationBuilder_;
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     * @return Whether the creation field is set.
     */
    public boolean hasCreation() {
      return creationBuilder_ != null || creation_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     * @return The creation.
     */
    public com.google.protobuf.Timestamp getCreation() {
      if (creationBuilder_ == null) {
        return creation_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : creation_;
      } else {
        return creationBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    public Builder setCreation(com.google.protobuf.Timestamp value) {
      if (creationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        creation_ = value;
        onChanged();
      } else {
        creationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    public Builder setCreation(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (creationBuilder_ == null) {
        creation_ = builderForValue.build();
        onChanged();
      } else {
        creationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    public Builder mergeCreation(com.google.protobuf.Timestamp value) {
      if (creationBuilder_ == null) {
        if (creation_ != null) {
          creation_ =
            com.google.protobuf.Timestamp.newBuilder(creation_).mergeFrom(value).buildPartial();
        } else {
          creation_ = value;
        }
        onChanged();
      } else {
        creationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    public Builder clearCreation() {
      if (creationBuilder_ == null) {
        creation_ = null;
        onChanged();
      } else {
        creation_ = null;
        creationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreationBuilder() {
      
      onChanged();
      return getCreationFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreationOrBuilder() {
      if (creationBuilder_ != null) {
        return creationBuilder_.getMessageOrBuilder();
      } else {
        return creation_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : creation_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp Creation = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreationFieldBuilder() {
      if (creationBuilder_ == null) {
        creationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreation(),
                getParentForChildren(),
                isClean());
        creation_ = null;
      }
      return creationBuilder_;
    }

    private java.lang.Object creator_ = "";
    /**
     * <code>string Creator = 10;</code>
     * @return The creator.
     */
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Creator = 10;</code>
     * @return The bytes for creator.
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Creator = 10;</code>
     * @param value The creator to set.
     * @return This builder for chaining.
     */
    public Builder setCreator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Creator = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreator() {
      
      creator_ = getDefaultInstance().getCreator();
      onChanged();
      return this;
    }
    /**
     * <code>string Creator = 10;</code>
     * @param value The bytes for creator to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creator_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object chat_ = "";
    /**
     * <code>string Chat = 12;</code>
     * @return The chat.
     */
    public java.lang.String getChat() {
      java.lang.Object ref = chat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Chat = 12;</code>
     * @return The bytes for chat.
     */
    public com.google.protobuf.ByteString
        getChatBytes() {
      java.lang.Object ref = chat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Chat = 12;</code>
     * @param value The chat to set.
     * @return This builder for chaining.
     */
    public Builder setChat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Chat = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearChat() {
      
      chat_ = getDefaultInstance().getChat();
      onChanged();
      return this;
    }
    /**
     * <code>string Chat = 12;</code>
     * @param value The bytes for chat to set.
     * @return This builder for chaining.
     */
    public Builder setChatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chat_ = value;
      onChanged();
      return this;
    }

    private com.example.authclientproto.PhysicalMeet physical_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.authclientproto.PhysicalMeet, com.example.authclientproto.PhysicalMeet.Builder, com.example.authclientproto.PhysicalMeetOrBuilder> physicalBuilder_;
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     * @return Whether the physical field is set.
     */
    public boolean hasPhysical() {
      return physicalBuilder_ != null || physical_ != null;
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     * @return The physical.
     */
    public com.example.authclientproto.PhysicalMeet getPhysical() {
      if (physicalBuilder_ == null) {
        return physical_ == null ? com.example.authclientproto.PhysicalMeet.getDefaultInstance() : physical_;
      } else {
        return physicalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    public Builder setPhysical(com.example.authclientproto.PhysicalMeet value) {
      if (physicalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        physical_ = value;
        onChanged();
      } else {
        physicalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    public Builder setPhysical(
        com.example.authclientproto.PhysicalMeet.Builder builderForValue) {
      if (physicalBuilder_ == null) {
        physical_ = builderForValue.build();
        onChanged();
      } else {
        physicalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    public Builder mergePhysical(com.example.authclientproto.PhysicalMeet value) {
      if (physicalBuilder_ == null) {
        if (physical_ != null) {
          physical_ =
            com.example.authclientproto.PhysicalMeet.newBuilder(physical_).mergeFrom(value).buildPartial();
        } else {
          physical_ = value;
        }
        onChanged();
      } else {
        physicalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    public Builder clearPhysical() {
      if (physicalBuilder_ == null) {
        physical_ = null;
        onChanged();
      } else {
        physical_ = null;
        physicalBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    public com.example.authclientproto.PhysicalMeet.Builder getPhysicalBuilder() {
      
      onChanged();
      return getPhysicalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    public com.example.authclientproto.PhysicalMeetOrBuilder getPhysicalOrBuilder() {
      if (physicalBuilder_ != null) {
        return physicalBuilder_.getMessageOrBuilder();
      } else {
        return physical_ == null ?
            com.example.authclientproto.PhysicalMeet.getDefaultInstance() : physical_;
      }
    }
    /**
     * <pre>
     * in person
     * </pre>
     *
     * <code>.pb.PhysicalMeet Physical = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.authclientproto.PhysicalMeet, com.example.authclientproto.PhysicalMeet.Builder, com.example.authclientproto.PhysicalMeetOrBuilder> 
        getPhysicalFieldBuilder() {
      if (physicalBuilder_ == null) {
        physicalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.authclientproto.PhysicalMeet, com.example.authclientproto.PhysicalMeet.Builder, com.example.authclientproto.PhysicalMeetOrBuilder>(
                getPhysical(),
                getParentForChildren(),
                isClean());
        physical_ = null;
      }
      return physicalBuilder_;
    }

    private com.example.authclientproto.OnlineMeet online_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.authclientproto.OnlineMeet, com.example.authclientproto.OnlineMeet.Builder, com.example.authclientproto.OnlineMeetOrBuilder> onlineBuilder_;
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     * @return Whether the online field is set.
     */
    public boolean hasOnline() {
      return onlineBuilder_ != null || online_ != null;
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     * @return The online.
     */
    public com.example.authclientproto.OnlineMeet getOnline() {
      if (onlineBuilder_ == null) {
        return online_ == null ? com.example.authclientproto.OnlineMeet.getDefaultInstance() : online_;
      } else {
        return onlineBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    public Builder setOnline(com.example.authclientproto.OnlineMeet value) {
      if (onlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        online_ = value;
        onChanged();
      } else {
        onlineBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    public Builder setOnline(
        com.example.authclientproto.OnlineMeet.Builder builderForValue) {
      if (onlineBuilder_ == null) {
        online_ = builderForValue.build();
        onChanged();
      } else {
        onlineBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    public Builder mergeOnline(com.example.authclientproto.OnlineMeet value) {
      if (onlineBuilder_ == null) {
        if (online_ != null) {
          online_ =
            com.example.authclientproto.OnlineMeet.newBuilder(online_).mergeFrom(value).buildPartial();
        } else {
          online_ = value;
        }
        onChanged();
      } else {
        onlineBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    public Builder clearOnline() {
      if (onlineBuilder_ == null) {
        online_ = null;
        onChanged();
      } else {
        online_ = null;
        onlineBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    public com.example.authclientproto.OnlineMeet.Builder getOnlineBuilder() {
      
      onChanged();
      return getOnlineFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    public com.example.authclientproto.OnlineMeetOrBuilder getOnlineOrBuilder() {
      if (onlineBuilder_ != null) {
        return onlineBuilder_.getMessageOrBuilder();
      } else {
        return online_ == null ?
            com.example.authclientproto.OnlineMeet.getDefaultInstance() : online_;
      }
    }
    /**
     * <pre>
     * online
     * </pre>
     *
     * <code>.pb.OnlineMeet Online = 30;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.authclientproto.OnlineMeet, com.example.authclientproto.OnlineMeet.Builder, com.example.authclientproto.OnlineMeetOrBuilder> 
        getOnlineFieldBuilder() {
      if (onlineBuilder_ == null) {
        onlineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.authclientproto.OnlineMeet, com.example.authclientproto.OnlineMeet.Builder, com.example.authclientproto.OnlineMeetOrBuilder>(
                getOnline(),
                getParentForChildren(),
                isClean());
        online_ = null;
      }
      return onlineBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.Event)
  }

  // @@protoc_insertion_point(class_scope:pb.Event)
  private static final com.example.authclientproto.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.authclientproto.Event();
  }

  public static com.example.authclientproto.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.authclientproto.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

