// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventChat.proto

package com.example.authclientproto;

/**
 * Protobuf type {@code pb.OnlineMeet}
 */
public final class OnlineMeet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.OnlineMeet)
    OnlineMeetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OnlineMeet.newBuilder() to construct.
  private OnlineMeet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OnlineMeet() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OnlineMeet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OnlineMeet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              supportLinks_ = com.google.protobuf.MapField.newMapField(
                  SupportLinksDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            supportLinks__ = input.readMessage(
                SupportLinksDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            supportLinks_.getMutableMap().put(
                supportLinks__.getKey(), supportLinks__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.authclientproto.ClientProto.internal_static_pb_OnlineMeet_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetSupportLinks();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.authclientproto.ClientProto.internal_static_pb_OnlineMeet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.authclientproto.OnlineMeet.class, com.example.authclientproto.OnlineMeet.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string Type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string Type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUPPORTLINKS_FIELD_NUMBER = 2;
  private static final class SupportLinksDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.example.authclientproto.ClientProto.internal_static_pb_OnlineMeet_SupportLinksEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> supportLinks_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetSupportLinks() {
    if (supportLinks_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SupportLinksDefaultEntryHolder.defaultEntry);
    }
    return supportLinks_;
  }

  public int getSupportLinksCount() {
    return internalGetSupportLinks().getMap().size();
  }
  /**
   * <pre>
   * instagram,discord, movie link
   * </pre>
   *
   * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
   */

  @java.lang.Override
  public boolean containsSupportLinks(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetSupportLinks().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSupportLinksMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getSupportLinks() {
    return getSupportLinksMap();
  }
  /**
   * <pre>
   * instagram,discord, movie link
   * </pre>
   *
   * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getSupportLinksMap() {
    return internalGetSupportLinks().getMap();
  }
  /**
   * <pre>
   * instagram,discord, movie link
   * </pre>
   *
   * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getSupportLinksOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSupportLinks().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * instagram,discord, movie link
   * </pre>
   *
   * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getSupportLinksOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSupportLinks().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetSupportLinks(),
        SupportLinksDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetSupportLinks().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      supportLinks__ = SupportLinksDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, supportLinks__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.authclientproto.OnlineMeet)) {
      return super.equals(obj);
    }
    com.example.authclientproto.OnlineMeet other = (com.example.authclientproto.OnlineMeet) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (!internalGetSupportLinks().equals(
        other.internalGetSupportLinks())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (!internalGetSupportLinks().getMap().isEmpty()) {
      hash = (37 * hash) + SUPPORTLINKS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSupportLinks().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.authclientproto.OnlineMeet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.authclientproto.OnlineMeet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.OnlineMeet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.OnlineMeet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.authclientproto.OnlineMeet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.OnlineMeet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.OnlineMeet)
      com.example.authclientproto.OnlineMeetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.authclientproto.ClientProto.internal_static_pb_OnlineMeet_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetSupportLinks();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableSupportLinks();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.authclientproto.ClientProto.internal_static_pb_OnlineMeet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.authclientproto.OnlineMeet.class, com.example.authclientproto.OnlineMeet.Builder.class);
    }

    // Construct using com.example.authclientproto.OnlineMeet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      internalGetMutableSupportLinks().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.authclientproto.ClientProto.internal_static_pb_OnlineMeet_descriptor;
    }

    @java.lang.Override
    public com.example.authclientproto.OnlineMeet getDefaultInstanceForType() {
      return com.example.authclientproto.OnlineMeet.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.authclientproto.OnlineMeet build() {
      com.example.authclientproto.OnlineMeet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.authclientproto.OnlineMeet buildPartial() {
      com.example.authclientproto.OnlineMeet result = new com.example.authclientproto.OnlineMeet(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.supportLinks_ = internalGetSupportLinks();
      result.supportLinks_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.authclientproto.OnlineMeet) {
        return mergeFrom((com.example.authclientproto.OnlineMeet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.authclientproto.OnlineMeet other) {
      if (other == com.example.authclientproto.OnlineMeet.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      internalGetMutableSupportLinks().mergeFrom(
          other.internalGetSupportLinks());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.authclientproto.OnlineMeet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.authclientproto.OnlineMeet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <code>string Type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string Type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> supportLinks_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSupportLinks() {
      if (supportLinks_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SupportLinksDefaultEntryHolder.defaultEntry);
      }
      return supportLinks_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableSupportLinks() {
      onChanged();;
      if (supportLinks_ == null) {
        supportLinks_ = com.google.protobuf.MapField.newMapField(
            SupportLinksDefaultEntryHolder.defaultEntry);
      }
      if (!supportLinks_.isMutable()) {
        supportLinks_ = supportLinks_.copy();
      }
      return supportLinks_;
    }

    public int getSupportLinksCount() {
      return internalGetSupportLinks().getMap().size();
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */

    @java.lang.Override
    public boolean containsSupportLinks(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSupportLinks().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSupportLinksMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSupportLinks() {
      return getSupportLinksMap();
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getSupportLinksMap() {
      return internalGetSupportLinks().getMap();
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getSupportLinksOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSupportLinks().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getSupportLinksOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSupportLinks().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSupportLinks() {
      internalGetMutableSupportLinks().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */

    public Builder removeSupportLinks(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSupportLinks().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableSupportLinks() {
      return internalGetMutableSupportLinks().getMutableMap();
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */
    public Builder putSupportLinks(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSupportLinks().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * instagram,discord, movie link
     * </pre>
     *
     * <code>map&lt;string, string&gt; SupportLinks = 2;</code>
     */

    public Builder putAllSupportLinks(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableSupportLinks().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.OnlineMeet)
  }

  // @@protoc_insertion_point(class_scope:pb.OnlineMeet)
  private static final com.example.authclientproto.OnlineMeet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.authclientproto.OnlineMeet();
  }

  public static com.example.authclientproto.OnlineMeet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OnlineMeet>
      PARSER = new com.google.protobuf.AbstractParser<OnlineMeet>() {
    @java.lang.Override
    public OnlineMeet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OnlineMeet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OnlineMeet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OnlineMeet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.authclientproto.OnlineMeet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

