// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventChat.proto

package com.example.authclientproto;

/**
 * Protobuf type {@code pb.PhysicalMeet}
 */
public final class PhysicalMeet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.PhysicalMeet)
    PhysicalMeetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PhysicalMeet.newBuilder() to construct.
  private PhysicalMeet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PhysicalMeet() {
    type_ = "";
    maps_ = "";
    locDescription_ = "";
    whatToBring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PhysicalMeet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PhysicalMeet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            maps_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            locDescription_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              whatToBring_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            whatToBring_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        whatToBring_ = whatToBring_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.authclientproto.ClientProto.internal_static_pb_PhysicalMeet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.authclientproto.ClientProto.internal_static_pb_PhysicalMeet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.authclientproto.PhysicalMeet.class, com.example.authclientproto.PhysicalMeet.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string Type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string Type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAPS_FIELD_NUMBER = 2;
  private volatile java.lang.Object maps_;
  /**
   * <pre>
   * Coordinates or street location
   * </pre>
   *
   * <code>string Maps = 2;</code>
   * @return The maps.
   */
  @java.lang.Override
  public java.lang.String getMaps() {
    java.lang.Object ref = maps_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      maps_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Coordinates or street location
   * </pre>
   *
   * <code>string Maps = 2;</code>
   * @return The bytes for maps.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMapsBytes() {
    java.lang.Object ref = maps_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      maps_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCDESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object locDescription_;
  /**
   * <pre>
   * how to get there in words
   * </pre>
   *
   * <code>string LocDescription = 3;</code>
   * @return The locDescription.
   */
  @java.lang.Override
  public java.lang.String getLocDescription() {
    java.lang.Object ref = locDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locDescription_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * how to get there in words
   * </pre>
   *
   * <code>string LocDescription = 3;</code>
   * @return The bytes for locDescription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocDescriptionBytes() {
    java.lang.Object ref = locDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WHATTOBRING_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList whatToBring_;
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @return A list containing the whatToBring.
   */
  public com.google.protobuf.ProtocolStringList
      getWhatToBringList() {
    return whatToBring_;
  }
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @return The count of whatToBring.
   */
  public int getWhatToBringCount() {
    return whatToBring_.size();
  }
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @param index The index of the element to return.
   * @return The whatToBring at the given index.
   */
  public java.lang.String getWhatToBring(int index) {
    return whatToBring_.get(index);
  }
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the whatToBring at the given index.
   */
  public com.google.protobuf.ByteString
      getWhatToBringBytes(int index) {
    return whatToBring_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!getMapsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, maps_);
    }
    if (!getLocDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, locDescription_);
    }
    for (int i = 0; i < whatToBring_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, whatToBring_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!getMapsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, maps_);
    }
    if (!getLocDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, locDescription_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < whatToBring_.size(); i++) {
        dataSize += computeStringSizeNoTag(whatToBring_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getWhatToBringList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.authclientproto.PhysicalMeet)) {
      return super.equals(obj);
    }
    com.example.authclientproto.PhysicalMeet other = (com.example.authclientproto.PhysicalMeet) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (!getMaps()
        .equals(other.getMaps())) return false;
    if (!getLocDescription()
        .equals(other.getLocDescription())) return false;
    if (!getWhatToBringList()
        .equals(other.getWhatToBringList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + MAPS_FIELD_NUMBER;
    hash = (53 * hash) + getMaps().hashCode();
    hash = (37 * hash) + LOCDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getLocDescription().hashCode();
    if (getWhatToBringCount() > 0) {
      hash = (37 * hash) + WHATTOBRING_FIELD_NUMBER;
      hash = (53 * hash) + getWhatToBringList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.authclientproto.PhysicalMeet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.authclientproto.PhysicalMeet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.PhysicalMeet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.authclientproto.PhysicalMeet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.authclientproto.PhysicalMeet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.PhysicalMeet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.PhysicalMeet)
      com.example.authclientproto.PhysicalMeetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.authclientproto.ClientProto.internal_static_pb_PhysicalMeet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.authclientproto.ClientProto.internal_static_pb_PhysicalMeet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.authclientproto.PhysicalMeet.class, com.example.authclientproto.PhysicalMeet.Builder.class);
    }

    // Construct using com.example.authclientproto.PhysicalMeet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      maps_ = "";

      locDescription_ = "";

      whatToBring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.authclientproto.ClientProto.internal_static_pb_PhysicalMeet_descriptor;
    }

    @java.lang.Override
    public com.example.authclientproto.PhysicalMeet getDefaultInstanceForType() {
      return com.example.authclientproto.PhysicalMeet.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.authclientproto.PhysicalMeet build() {
      com.example.authclientproto.PhysicalMeet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.authclientproto.PhysicalMeet buildPartial() {
      com.example.authclientproto.PhysicalMeet result = new com.example.authclientproto.PhysicalMeet(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.maps_ = maps_;
      result.locDescription_ = locDescription_;
      if (((bitField0_ & 0x00000001) != 0)) {
        whatToBring_ = whatToBring_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.whatToBring_ = whatToBring_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.authclientproto.PhysicalMeet) {
        return mergeFrom((com.example.authclientproto.PhysicalMeet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.authclientproto.PhysicalMeet other) {
      if (other == com.example.authclientproto.PhysicalMeet.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getMaps().isEmpty()) {
        maps_ = other.maps_;
        onChanged();
      }
      if (!other.getLocDescription().isEmpty()) {
        locDescription_ = other.locDescription_;
        onChanged();
      }
      if (!other.whatToBring_.isEmpty()) {
        if (whatToBring_.isEmpty()) {
          whatToBring_ = other.whatToBring_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureWhatToBringIsMutable();
          whatToBring_.addAll(other.whatToBring_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.authclientproto.PhysicalMeet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.authclientproto.PhysicalMeet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <code>string Type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string Type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object maps_ = "";
    /**
     * <pre>
     * Coordinates or street location
     * </pre>
     *
     * <code>string Maps = 2;</code>
     * @return The maps.
     */
    public java.lang.String getMaps() {
      java.lang.Object ref = maps_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maps_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Coordinates or street location
     * </pre>
     *
     * <code>string Maps = 2;</code>
     * @return The bytes for maps.
     */
    public com.google.protobuf.ByteString
        getMapsBytes() {
      java.lang.Object ref = maps_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maps_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Coordinates or street location
     * </pre>
     *
     * <code>string Maps = 2;</code>
     * @param value The maps to set.
     * @return This builder for chaining.
     */
    public Builder setMaps(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      maps_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Coordinates or street location
     * </pre>
     *
     * <code>string Maps = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaps() {
      
      maps_ = getDefaultInstance().getMaps();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Coordinates or street location
     * </pre>
     *
     * <code>string Maps = 2;</code>
     * @param value The bytes for maps to set.
     * @return This builder for chaining.
     */
    public Builder setMapsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      maps_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object locDescription_ = "";
    /**
     * <pre>
     * how to get there in words
     * </pre>
     *
     * <code>string LocDescription = 3;</code>
     * @return The locDescription.
     */
    public java.lang.String getLocDescription() {
      java.lang.Object ref = locDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * how to get there in words
     * </pre>
     *
     * <code>string LocDescription = 3;</code>
     * @return The bytes for locDescription.
     */
    public com.google.protobuf.ByteString
        getLocDescriptionBytes() {
      java.lang.Object ref = locDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * how to get there in words
     * </pre>
     *
     * <code>string LocDescription = 3;</code>
     * @param value The locDescription to set.
     * @return This builder for chaining.
     */
    public Builder setLocDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      locDescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * how to get there in words
     * </pre>
     *
     * <code>string LocDescription = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocDescription() {
      
      locDescription_ = getDefaultInstance().getLocDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * how to get there in words
     * </pre>
     *
     * <code>string LocDescription = 3;</code>
     * @param value The bytes for locDescription to set.
     * @return This builder for chaining.
     */
    public Builder setLocDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      locDescription_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList whatToBring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureWhatToBringIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        whatToBring_ = new com.google.protobuf.LazyStringArrayList(whatToBring_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @return A list containing the whatToBring.
     */
    public com.google.protobuf.ProtocolStringList
        getWhatToBringList() {
      return whatToBring_.getUnmodifiableView();
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @return The count of whatToBring.
     */
    public int getWhatToBringCount() {
      return whatToBring_.size();
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @param index The index of the element to return.
     * @return The whatToBring at the given index.
     */
    public java.lang.String getWhatToBring(int index) {
      return whatToBring_.get(index);
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the whatToBring at the given index.
     */
    public com.google.protobuf.ByteString
        getWhatToBringBytes(int index) {
      return whatToBring_.getByteString(index);
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @param index The index to set the value at.
     * @param value The whatToBring to set.
     * @return This builder for chaining.
     */
    public Builder setWhatToBring(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWhatToBringIsMutable();
      whatToBring_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @param value The whatToBring to add.
     * @return This builder for chaining.
     */
    public Builder addWhatToBring(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWhatToBringIsMutable();
      whatToBring_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @param values The whatToBring to add.
     * @return This builder for chaining.
     */
    public Builder addAllWhatToBring(
        java.lang.Iterable<java.lang.String> values) {
      ensureWhatToBringIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, whatToBring_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhatToBring() {
      whatToBring_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string WhatToBring = 4;</code>
     * @param value The bytes of the whatToBring to add.
     * @return This builder for chaining.
     */
    public Builder addWhatToBringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureWhatToBringIsMutable();
      whatToBring_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.PhysicalMeet)
  }

  // @@protoc_insertion_point(class_scope:pb.PhysicalMeet)
  private static final com.example.authclientproto.PhysicalMeet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.authclientproto.PhysicalMeet();
  }

  public static com.example.authclientproto.PhysicalMeet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PhysicalMeet>
      PARSER = new com.google.protobuf.AbstractParser<PhysicalMeet>() {
    @java.lang.Override
    public PhysicalMeet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PhysicalMeet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PhysicalMeet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PhysicalMeet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.authclientproto.PhysicalMeet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

