// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventChat.proto

package com.example.authclientproto;

public interface PhysicalMeetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.PhysicalMeet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string Type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * Coordinates or street location
   * </pre>
   *
   * <code>string Maps = 2;</code>
   * @return The maps.
   */
  java.lang.String getMaps();
  /**
   * <pre>
   * Coordinates or street location
   * </pre>
   *
   * <code>string Maps = 2;</code>
   * @return The bytes for maps.
   */
  com.google.protobuf.ByteString
      getMapsBytes();

  /**
   * <pre>
   * how to get there in words
   * </pre>
   *
   * <code>string LocDescription = 3;</code>
   * @return The locDescription.
   */
  java.lang.String getLocDescription();
  /**
   * <pre>
   * how to get there in words
   * </pre>
   *
   * <code>string LocDescription = 3;</code>
   * @return The bytes for locDescription.
   */
  com.google.protobuf.ByteString
      getLocDescriptionBytes();

  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @return A list containing the whatToBring.
   */
  java.util.List<java.lang.String>
      getWhatToBringList();
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @return The count of whatToBring.
   */
  int getWhatToBringCount();
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @param index The index of the element to return.
   * @return The whatToBring at the given index.
   */
  java.lang.String getWhatToBring(int index);
  /**
   * <code>repeated string WhatToBring = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the whatToBring at the given index.
   */
  com.google.protobuf.ByteString
      getWhatToBringBytes(int index);
}
